# Site settings
title: Andrew Strovers' Test Blog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A daily journal where Andrew writes about his journey as a student in Omaha Code School
url: "http://your_github_username.github.io"
twitter_username: your_twitter
github_username:  ADStrovers

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"